{
 "title": "Sensor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM sensor\nWHERE\n  $__timeFilter(datetime) AND\n  type = 'temperature'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current humidity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM sensor\nWHERE\n  $__timeFilter(datetime) AND\n  type = 'humidity'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  s.datetime AS \"time\",\n  CASE WHEN d.name is NULL THEN CAST(s.device_id AS VARCHAR) ELSE d.name END AS metric,\n  s.value\nFROM sensor AS s\nLEFT JOIN device AS d\n  ON (s.device_id = d.device_id)\nWHERE\n  $__timeFilter(datetime) AND\n  s.type = 'temperature'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  s.datetime AS \"time\",\n  CASE WHEN d.name is NULL THEN CAST(s.device_id AS VARCHAR) ELSE d.name END AS metric,\n  s.value\nFROM sensor AS s\nLEFT JOIN device AS d\n  ON (s.device_id = d.device_id)\nWHERE\n  $__timeFilter(datetime) AND\n  s.type = 'humidity'\nORDER BY 1,2"
    }
   ]
  }
 ]
}