version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"

  node-red:
    image: nodered/node-red-docker:slim-v10
    ports:
      - "1880:1880"
    volumes:
      - node-red:/data

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:6.2.5
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  postgres:
  node-red:
  grafana: